export const BankName = {
  ABAY: "abay",
  ABYSSINIA: "abyssinia",
  BUNNA: "bunna",
  AWASH: "awash",
};

export const location = [
  {
    id: 1,
    name: "Addis Ababa",
    type: "Region",
    cities: [
      {
        id: 999,
        name: "Addis Ababa City",
        subCities: [
          { id: 15, name: "Addis Ketema" },
          { id: 16, name: "Akaky Kaliti" },
          { id: 17, name: "Arada" },
          { id: 18, name: "Bole" },
          { id: 19, name: "Gullele" },
          { id: 20, name: "Kirkos" },
          { id: 21, name: "Kolfe Keranio" },
          { id: 22, name: "Lideta" },
          { id: 23, name: "Nifas Silk-Lafto" },
          { id: 24, name: "Yeka" },
          { id: 25, name: "Lemi Kura" },
        ],
      },
    ],
  },

  {
    id: 2,
    name: "Afar",
    type: "Region",
    cities: [
      { id: 26, name: "Semera Logia", type: "City", subCities: [] },
      { id: 27, name: "Asaita", type: "City", subCities: [] },
      { id: 45, name: "Awash", type: "City", subCities: [] },
      { id: 49, name: "Meteka", type: "City", subCities: [] },
    ],
  },

  {
    id: 3,
    name: "Somali",
    type: "Region",
    cities: [
      { id: 775, name: "Qabribayax", type: "City", subCities: [] },
      { id: 778, name: "Tog Wajaale(Wajaale)", type: "City", subCities: [] },
      { id: 787, name: "Shekosh", type: "City", subCities: [] },
      { id: 811, name: "Araarso", type: "City", subCities: [] },
      { id: 842, name: "Biki", type: "City", subCities: [] },
      { id: 839, name: "Adhigale", type: "City", subCities: [] },
    ],
  },

  {
    id: 4,
    name: "Amhara",
    type: "Region",
    cities: [
      { id: 63, name: "Dangila", type: "City", subCities: [] },
      { id: 75, name: "Dejen", type: "City", subCities: [] },
      { id: 86, name: "Mota", type: "City", subCities: [] },
      { id: 91, name: "Dabat", type: "City", subCities: [] },
      { id: 92, name: "Debarq", type: "City", subCities: [] },
      { id: 98, name: "Metemma", type: "City", subCities: [] },
      { id: 109, name: "Ankober", type: "City", subCities: [] },
      { id: 137, name: "Kobo", type: "City", subCities: [] },
      { id: 141, name: "Weldiya", type: "City", subCities: [] },
      { id: 142, name: "Lalibela", type: "City", subCities: [] },
      { id: 144, name: "Baati", type: "City", subCities: [] },
      { id: 148, name: "Kemise", type: "City", subCities: [] },
      { id: 149, name: "Debre Tabor", type: "City", subCities: [] },
      { id: 162, name: "Debre Sina", type: "City", subCities: [] },
      { id: 163, name: "Dessie", type: "City", subCities: [] },
      { id: 168, name: "Kombolcha", type: "City", subCities: [] },
      { id: 184, name: "Soqota", type: "City", subCities: [] },
      { id: 185, name: "Soqota", type: "City", subCities: [] }, // duplicate kept
      { id: 187, name: "Bure", type: "City", subCities: [] },
      { id: 190, name: "Dembecha", type: "City", subCities: [] },
      { id: 192, name: "Finote Selam", type: "City", subCities: [] },
    ],
  },
  {
    id: 5,
    name: "Benishangul-gumiz",
    type: "Region",
    cities: [], // no cities found in your list
  },
  {
    id: 6,
    name: "Dire Dawa",
    type: "Region",
    cities: [], // no cities from your list match Dire Dawa
  },
  {
    id: 7,
    name: "Gambella",
    type: "Region",
    cities: [], // no cities provided for Gambella
  },
  {
    id: 8,
    name: "Harrari",
    type: "Region",
    cities: [], // no Harari cities in dataset
  },

  {
    id: 9,
    name: "Oromia",
    type: "Region",
    cities: [
      { id: 263, name: "Asella", type: "City", subCities: [] },
      { id: 265, name: "Aseko", type: "City", subCities: [] },
      { id: 280, name: "Robe", type: "City", subCities: [] },
      { id: 281, name: "Seru", type: "City", subCities: [] },
      { id: 282, name: "Sire", type: "City", subCities: [] },
      { id: 286, name: "Tiyo", type: "City", subCities: [] },
      { id: 287, name: "Goba", type: "City", subCities: [] },
      { id: 294, name: "Gasera", type: "City", subCities: [] },
      { id: 295, name: "Ginir", type: "City", subCities: [] },
      { id: 296, name: "Goba", type: "City", subCities: [] }, // duplicate
      { id: 298, name: "Goro", type: "City", subCities: [] },
      { id: 302, name: "Meda Welabu", type: "City", subCities: [] },
      { id: 303, name: "Raytu", type: "City", subCities: [] },
      { id: 306, name: "Sinana", type: "City", subCities: [] },
      { id: 309, name: "Bule Hora", type: "City", subCities: [] },
      { id: 310, name: "Dillo", type: "City", subCities: [] },
      { id: 316, name: "Moyale", type: "City", subCities: [] },
      { id: 317, name: "Teltele", type: "City", subCities: [] },
      { id: 318, name: "Yabelo", type: "City", subCities: [] },
      { id: 319, name: "Bedele", type: "City", subCities: [] },
      { id: 320, name: "Babile", type: "City", subCities: [] },
      { id: 323, name: "Dadar", type: "City", subCities: [] },
      { id: 329, name: "Harro Maya", type: "City", subCities: [] },
      { id: 336, name: "Meta", type: "City", subCities: [] },
      { id: 339, name: "Ada'a", type: "City", subCities: [] },
      { id: 341, name: "Batu", type: "City", subCities: [] },
      { id: 342, name: "Bishoftu", type: "City", subCities: [] },
      { id: 343, name: "Bora", type: "City", subCities: [] },
      { id: 347, name: "Gimbichu", type: "City", subCities: [] },
      { id: 362, name: "Nekemte", type: "City", subCities: [] },
      { id: 368, name: "Adola", type: "City", subCities: [] },
      { id: 378, name: "Negele Borena", type: "City", subCities: [] },
      { id: 379, name: "Odo Shakiso", type: "City", subCities: [] },
      { id: 384, name: "Amuru", type: "City", subCities: [] },
      { id: 385, name: "Guduru", type: "City", subCities: [] },
      { id: 391, name: "Shambu", type: "City", subCities: [] },
      { id: 395, name: "Bedele", type: "City", subCities: [] }, // duplicate
      { id: 399, name: "Bure", type: "City", subCities: [] },
      { id: 410, name: "Hurumu", type: "City", subCities: [] },
      { id: 413, name: "Metu", type: "City", subCities: [] },
      { id: 416, name: "Yayu", type: "City", subCities: [] },
      { id: 417, name: "Agaro", type: "City", subCities: [] },
      { id: 419, name: "Dedo", type: "City", subCities: [] },
      { id: 428, name: "Seka Chekorsa", type: "City", subCities: [] },
      { id: 432, name: "Sokoru", type: "City", subCities: [] },
      { id: 437, name: "Dembidolo", type: "City", subCities: [] },
      { id: 439, name: "Gidami", type: "City", subCities: [] },
      { id: 445, name: "Abichu", type: "City", subCities: [] },
      { id: 446, name: "Aleltu", type: "City", subCities: [] },
      { id: 447, name: "Degem", type: "City", subCities: [] },
      { id: 448, name: "Dera", type: "City", subCities: [] },
      { id: 449, name: "Fiche", type: "City", subCities: [] },
      { id: 458, name: "Yaya Gulele", type: "City", subCities: [] },
      { id: 460, name: "Becho", type: "City", subCities: [] },
      { id: 469, name: "Waliso", type: "City", subCities: [] },
      { id: 470, name: "Wanchi", type: "City", subCities: [] },
      { id: 471, name: "Adaba", type: "City", subCities: [] },
      { id: 472, name: "Arsi Negele", type: "City", subCities: [] },
      { id: 473, name: "Dodola", type: "City", subCities: [] },
      { id: 475, name: "Kofele", type: "City", subCities: [] },
      { id: 482, name: "Shashamane", type: "City", subCities: [] },
      { id: 484, name: "Badessa", type: "City", subCities: [] },
      { id: 485, name: "Boke", type: "City", subCities: [] },
      { id: 487, name: "Chiro", type: "City", subCities: [] },
      { id: 495, name: "Mieso", type: "City", subCities: [] },
      { id: 498, name: "Hirna", type: "City", subCities: [] },
      { id: 499, name: "Abuna Ginde Beret", type: "City", subCities: [] },
      { id: 500, name: "Adda Berga", type: "City", subCities: [] },
      { id: 501, name: "Ambo", type: "City", subCities: [] },
      { id: 505, name: "Dendi", type: "City", subCities: [] },
      { id: 506, name: "Dire Enchini", type: "City", subCities: [] },
      { id: 507, name: "Ejerie", type: "City", subCities: [] },
      { id: 509, name: "Ginde Beret", type: "City", subCities: [] },
      { id: 511, name: "Jeldu", type: "City", subCities: [] },
      { id: 513, name: "Meta Robi", type: "City", subCities: [] },
      { id: 525, name: "Gimbi", type: "City", subCities: [] },
      { id: 534, name: "Nejo", type: "City", subCities: [] },
      { id: 539, name: "Akaki", type: "City", subCities: [] },
      { id: 541, name: "Burayu", type: "City", subCities: [] },
      { id: 542, name: "Holeta", type: "City", subCities: [] },
      { id: 543, name: "Koye Feche", type: "City", subCities: [] },
      { id: 544, name: "Mulo", type: "City", subCities: [] },
      { id: 545, name: "Sebeta", type: "City", subCities: [] },
      { id: 546, name: "Sendafa", type: "City", subCities: [] },
      { id: 547, name: "Sululta", type: "City", subCities: [] },
    ],
  },
  {
    id: 10,
    name: "S.N.N.P.R",
    type: "Region",
    cities: [
      { id: 553, name: "Chencha", type: "City", subCities: [] },
      { id: 565, name: "Sawula", type: "City", subCities: [] },
      { id: 567, name: "Dila", type: "City", subCities: [] },
      { id: 592, name: "Hosaena", type: "City", subCities: [] },
      { id: 602, name: "Durame", type: "City", subCities: [] },
      { id: 613, name: "Silite", type: "City", subCities: [] },
      { id: 627, name: "Sodo", type: "City", subCities: [] },
      { id: 653, name: "Konso", type: "City", subCities: [] },
    ],
  },

  {
    id: 11,
    name: "S.W.E.P.R",
    type: "Region",
    cities: [
      { id: 660, name: "Mizan Teferi", type: "City", subCities: [] },
      { id: 664, name: "Teppi", type: "City", subCities: [] },
      { id: 674, name: "Maji", type: "City", subCities: [] },
      { id: 676, name: "Bonga", type: "City", subCities: [] },
    ],
  },

  {
    id: 12,
    name: "Sidama",
    type: "Region",
    cities: [
      { id: 688, name: "Yirgalem", type: "City", subCities: [] },
      { id: 689, name: "Aleta Wendo", type: "City", subCities: [] },
    ],
  },

  {
    id: 13,
    name: "Tigray",
    type: "Region",
    cities: [
      { id: 711, name: "Adwa", type: "City", subCities: [] },
      { id: 722, name: "Wukro", type: "City", subCities: [] },
      { id: 734, name: "Sheraro", type: "City", subCities: [] },
      { id: 744, name: "Maychew", type: "City", subCities: [] },
      { id: 747, name: "Korem", type: "City", subCities: [] },
    ],
  },
];

export const gender = [
  {
    id: 181,
    name: "Male",
    type: "Gender",
  },
  {
    id: 182,
    name: "Female",
    type: "Gender",
  },
];

export const maritalStatus = [
  {
    id: 183,
    name: "Single",
    type: "Marital Status",
  },
  {
    id: 184,
    name: "Married",
    type: "Marital Status",
  },
];
